name: Auto Release for Main Branch

on:
  push:
    branches:
      - main  # Trigger on pushes to main (e.g., after a PR is merged)

jobs:
  validate-version:
    name: Validate Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch main branch into a detached HEAD
        run: |
          git fetch origin main
          git checkout origin/main -b temp-main-branch

      - name: Get VERSION from patch branch
        id: get_patch_version
        run: |
          VERSION=$(grep -m 1 -oP '^VERSION=\K.*' VERSION_FILE)
          echo "patch_version=$VERSION" >> $GITHUB_ENV

      - name: Get VERSION from main branch
        id: get_main_version
        run: |
          git checkout temp-main-branch
          VERSION=$(grep -m 1 -oP '^VERSION=\K.*' VERSION_FILE)
          echo "main_version=$VERSION" >> $GITHUB_ENV

      - name: Validate version increment
        id: validate_version
        run: |
          patch_version=$patch_version
          main_version=$main_version

          # Extract PATCH numbers
          main_patch=$(echo "$main_version" | awk -F '.' '{print $3}')
          patch_patch=$(echo "$patch_version" | awk -F '.' '{print $3}')



  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: validate-version

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Extract Version from `pv_opt.py`
      - name: Extract Version
        id: extract_version
        run: |
          # Extract the VERSION variable from pv_opt.py
          VERSION=$(grep -oP '(?<=^VERSION = ")[^"]+' apps/pv_opt/pv_opt.py)
          if [ -z "$VERSION" ]; then
            echo "Error: VERSION not found in apps/pv_opt/pv_opt.py"
            exit 1
          fi
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV  # Save to environment file

      # Step 3: Create GitHub Release
      - name: Create GitHub Release
        if: |
          github.event_name == 'push' || 
          (github.event_name == 'pull_request_review' && github.event.review.state == 'approved')
        uses: actions/create-release@v1
        with:
          tag_name: "v${{ env.version }}"
          release_name: "Release v${{ env.version }}"
          body: |
            ## Changes
            This release was automatically generated.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
